version: "3"

networks:
  psotoolnet:
    external: false
    driver_opts:
      com.docker.network.bridge.name: psotool-bridge

services:
  psotoolsrvr:
    build: .
    environment:
      - DB_TYPE=postgres
      - PGHOST=db
      - PGDATABASE=psotool
      - PGUSER=psotool
      - PGPASS=password
    restart: always
    networks:
      - psotoolnet
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "6789:3000"
    depends_on:
      - psotooldb

  psotooldb:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=psotool
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=psotool
    networks:
      - psotoolnet
    volumes:
      - ./postgres:/var/lib/postgresql/data
